services:
  app:
    image: bellsoft/liberica-openjdk-alpine:21
    container_name: clinic_app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PG_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      GRADLE_USER_HOME: /cache
    ports:
      - "${SERVICE_PORT}:8080"
    depends_on:
      - postgres
      - flyway
    volumes:
      - ./backend:/app
      - /app/.gradle
      - gradle_cache:/cache
    working_dir: /app
    command: >
      sh -c "chmod +x gradlew && 
             ./gradlew clean :service:bootJar -x test --no-daemon && 
             java -jar service/build/libs/service-0.0.1-SNAPSHOT.jar"

  postgres:
    image: postgres:15-alpine
    container_name: clinic_db
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: clinic-flyway
    command:
      - migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${PG_DATABASE}
      FLYWAY_USER: ${PG_USER}
      FLYWAY_PASSWORD: ${PG_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
    volumes:
      - ./backend/database/migrations:/flyway/sql
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:${SERVICE_PORT}
    container_name: clinic_frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  db_data:
  gradle_cache:
